language: php
php:
  - 5.4
  - 5.5.9
  - 5.5
  - 5.6
  - 7.0
  - hhvm

env:
  global:
    - brute_force=no

matrix:
  include:
    - php: hhvm
      env: brute_force=yes

install:
  - composer install --no-interaction --prefer-source
script: vendor/bin/phpunit
  - if [[ $brute_force = 'no' ]]; then vendor/bin/phpunit --exclude-group=brute_force; fi
  - if [[ $brute_force = 'yes' ]]; then vendor/bin/phpunit; fi
